name: Build PonWrt For AN7581

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com
  REPO_BRANCH: master
  CONFIG_FILE: configs/an7581.config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/powershell /usr/share/swift /pypy /libs /viewer
        sudo bash -c 'bash <(curl -s https://immortalwrt.org)'
        sudo timedatectl set-timezone "${{ env.TZ }}"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -h
        git clone $REPO_URL -b $REPO_BRANCH ponwrt
        ln -sf /workdir/ponwrt $GITHUB_WORKSPACE/ponwrt

    - name: Update & Install feeds
      cd ponwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom configuration
      cd ponwrt
      run: |
        if [ -f "../$CONFIG_FILE" ]; then
          cp "../$CONFIG_FILE" .config
        elif [ -f "$CONFIG_FILE" ]; then
          cp "$CONFIG_FILE" .config
        else
          echo "Config file not found!" && exit 1
        fi
        make defconfig

    - name: Compile the firmware
      id: compile
      cd ponwrt
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      if: steps.compile.outputs.status == 'success'
      run: df -h

    - name: Upload bin directory
      uses: actions/artifacts@v4
      if: steps.compile.outputs.status == 'success'
      with:
        name: PonWrt_AN7581_firmware
        path: ponwrt/bin/targets/airoha/an7581/
